[tool.poetry]
name = "matrix-saml-strip-hostname"
version = "0.2.0"
description = "SAML mapping provider to strip hostnames from mxids"
authors = ["Sylvain Fankhauser <sephi@fhtagn.top>"]
repository = "https://github.com/sephii/matrix-saml-strip-hostname"
readme = "README.rst"
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
